name: Aggregate

on: [push]
    # schedule:
    # - cron: '0 0 * * *'


jobs:
    aggregate:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install
        - name: Aggregate the data
          run: |
            poetry run workflowhub-graph-source-crates
            poetry run workflowhub-graph-merge merged.ttl
            # TODO store artifact, to zenodo? to github release (tag daily, make )? to gh pages?


        - name: Get current date
          id: date
          run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
          
        - name: Create release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            tag: nightly-tag-${{ steps.date.outputs.date }}
          run: |
            gh release create "$tag" \
                --repo="$GITHUB_REPOSITORY" \
                --title="${tag#v}" \
                --generate-notes            
